# Generated by Django 3.2.8 on 2022-08-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20220805_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='linkto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
